# Stage 1 - Build the React app
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

# Vite outputs to /app/dist
RUN npm run build

# Stage 2 - Serve with Nginx
FROM nginx:1.25.2-alpine-slim

# Copy built files from Stage 1 to Nginx's serve directory
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
