version: '3.8'

services:
  # Node.js/Express Backend
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DB_URL=mongodb://admin:secret123@mongodb_server:27017/redisDB?authSource=admin
    depends_on:
      - mongodb

  # React Frontend (Vite + Nginx)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '80:80'
    depends_on:
      - server

  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret123
    ports:
      - '27017:27017'
